/// The Product namespace an Agent Adapter is configured for (e.g. "claude-code").
/// Identity, never presentation: two sessions only share identity when they
/// share both this and a `NativeSessionID`.
public struct ProductNamespace: Hashable, Sendable, Codable {
    public let rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }
}

/// The stable native identifier an Agent Product assigned to one Agent
/// Session. Supplied by the Product, never invented locally.
public struct NativeSessionID: Hashable, Sendable, Codable {
    public let rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }
}

/// Agent Session identity per ADR 0001: Product namespace plus stable
/// Product-native identifier only. Nothing else may create or merge identity.
public struct AgentSessionIdentity: Hashable, Sendable, Codable {
    public let productNamespace: ProductNamespace
    public let nativeSessionID: NativeSessionID

    public init(productNamespace: ProductNamespace, nativeSessionID: NativeSessionID) {
        self.productNamespace = productNamespace
        self.nativeSessionID = nativeSessionID
    }
}

/// One configured Integration Installation instance. Routing provenance,
/// never a replacement for Agent Session identity.
public struct IntegrationInstanceID: Hashable, Sendable, Codable {
    public let rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }
}

/// Identifies one immutable `NegotiationSnapshot`. Generated by the outer
/// caller (never by `SessionDomain`, which calls no ID source) and carried
/// as opaque data thereafter.
public struct NegotiationSnapshotID: Hashable, Sendable, Codable {
    public let rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }
}

/// Major/minor Adapter contract version. Major changes may alter meaning or
/// required fields; minor changes only add optional fields/capabilities.
public struct ContractVersion: Hashable, Sendable, Codable {
    public let major: Int
    public let minor: Int

    public init(major: Int, minor: Int) {
        self.major = major
        self.minor = minor
    }
}
